### PR TITLE
Fix the function for printing the queue

### PR DESCRIPTION
**Pull request by Xi-Row**
If this pull request (PR) pertains to **Chinese-to-English translation**, please confirm that you have read the contribution guidelines and complete the checklist below:

- [ ] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [ ] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.

If this pull request (PR) is associated with **coding or code transpilation**, please attach the relevant console outputs to the PR and complete the following checklist:

- [ ] I have thoroughly reviewed the code, focusing on its formatting, comments, indentation, and file headers.
- [ ] I have confirmed that the code execution outputs are consistent with those produced by the reference code (Python or Java).
- [ ] The code is designed to be compatible on standard operating systems, including Windows, macOS, and Ubuntu.

### CODE REVIEW

**Comment by Xi-Row** [comment]
[修改说明.md](https://github.com/user-attachments/files/17919687/default.md)

**Comment by krahets** [comment]
image

Hi, I cannot see the screenshots. Could you paste them directly into the comment box of this page?

**Comment by Xi-Row** [comment]
我按md文件中的顺序发出来了

**Comment by Xi-Row** [comment]
[https://github.com/Xi-Row/Image/blob/886332b35514f78a60167e4cdcfd81efaf042373/%E4%BF%AE%E6%94%B9%E8%AF%B4%E6%98%8E.md](url)

**Comment by Xi-Row** [comment]
https://github.com/Xi-Row/Image/blob/886332b35514f78a60167e4cdcfd81efaf042373/%E4%BF%AE%E6%94%B9%E8%AF%B4%E6%98%8E.md

**Comment by Xi-Row** [comment]
[修改说明](https://github.com/Xi-Row/Image/blob/886332b35514f78a60167e4cdcfd81efaf042373/%E4%BF%AE%E6%94%B9%E8%AF%B4%E6%98%8E.md)

**Comment by krahets** [comment]
Please add your description also into the comment box.

**Comment by krahets** [comment]
Thank you for the PR!

Referring to the implementations in other programming languages, we decided to add the toArray() function instead. Here are the test results:

```sh
❯ hello-algo/codes/c/build/chapter_stack_and_queue/array_deque
双向队列 deque = [3, 2, 5]
队首元素 peekFirst = 3
队尾元素 peekLast = 5
元素 4 队尾入队后 deque = [3, 2, 5, 4]
元素 1 队首入队后 deque = [3, 2, 5, 4, 0]
队尾出队元素 = 4 ，队尾出队后 deque= [3, 2, 5, 4]
队首出队元素 = 1 ，队首出队后 deque= [3, 2, 5]
双向队列长度 size = 3
队列是否为空 = false

❯ hello-algo/codes/c/build/chapter_stack_and_queue/array_deque
双向队列 deque = [3, 2, 5]
队首元素 peekFirst = 3
队尾元素 peekLast = 5
元素 4 队尾入队后 deque = [3, 2, 5, 4]
元素 1 队首入队后 deque = [1, 3, 2, 5, 4]
队尾出队元素 = 4 ，队尾出队后 deque= [1, 3, 2, 5]
队首出队元素 = 1 ，队首出队后 deque= [3, 2, 5]
双向队列长度 size = 3
队列是否为空 = false
```

**Review by krahets — APPROVED** [review]

**Comment by Xi-Row** [comment]
***@***.***
元素1队首入队是不是还是打印错误了（？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Yudong Jin ***@***.***>
发送时间: Wednesday, December 4, 2024 7:36:48 PM
收件人: krahets/hello-algo ***@***.***>
抄送: pzpz ***@***.***>; Author ***@***.***>
主题: Re: [krahets/hello-algo] Fix the function for printing the queue (PR #1573)


Thank you for the PR!

Referring to the implementations in other programming languages, we decided to add the toArray() function instead. Here are the test results:

❯ hello-algo/codes/c/build/chapter_stack_and_queue/array_deque
双向队列 deque = [3, 2, 5]
队首元素 peekFirst = 3
队尾元素 peekLast = 5
元素 4 队尾入队后 deque = [3, 2, 5, 4]
元素 1 队首入队后 deque = [3, 2, 5, 4, 0]
队尾出队元素 = 4 ，队尾出队后 deque= [3, 2, 5, 4]
队首出队元素 = 1 ，队首出队后 deque= [3, 2, 5]
双向队列长度 size = 3
队列是否为空 = false

❯ hello-algo/codes/c/build/chapter_stack_and_queue/array_deque
双向队列 deque = [3, 2, 5]
队首元素 peekFirst = 3
队尾元素 peekLast = 5
元素 4 队尾入队后 deque = [3, 2, 5, 4]
元素 1 队首入队后 deque = [1, 3, 2, 5, 4]
队尾出队元素 = 4 ，队尾出队后 deque= [1, 3, 2, 5]
队首出队元素 = 1 ，队首出队后 deque= [3, 2, 5]
双向队列长度 size = 3
队列是否为空 = false

**Comment by krahets** [comment]
@Xi-Row Please check the latest version of the comments.

**Pull request merged**
