### PR TITLE
test(binary_search_tree): update test param

### PR DESCRIPTION
**Pull request by guowei-gong**
use param value 7, not 5, function test param value with param value in example picture as same.

image

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Thanks! Could you help update all the languages?

**Comment by guowei-gong** [comment]
> Thanks! Could you help update all the languages?

sure. 😄

**Comment by krahets** [comment]
Hi, have you updated this PR?~

**Comment by guowei-gong** [comment]
> Hi, have you updated this PR?~

sry, I was lazy. I'll update it now 😭

**Comment by guowei-gong** [comment]
@krahets updated. sorry again

**Review by krahets — APPROVED** [review]
Thanks!

**Pull request merged**
