### PR TITLE
fix: bug fixes for array_hash_map.c and counting_sort.c

### PR DESCRIPTION
**Pull request by Gonglja**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference code.
- [x] I've checked the code (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by Gonglja** [comment]
https://github.com/krahets/hello-algo/discussions/78/#discussioncomment-7611511
https://github.com/krahets/hello-algo/discussions/428/#discussioncomment-7637613

**Review by krahets — APPROVED** [review]
Thanks for the fix!

**Comment by krahets** [comment]
I would recommend you re-fork the repo to make a clearer commit history.

**Comment by Gonglja** [comment]
OK, let me know how to achieve it.

发自我的iPhone

在 2023年11月26日，22:59，Yudong Jin ***@***.***> 写道：

﻿

I would recommend you re-fork the repo to make a clearer commit history.

**Comment by krahets** [comment]
@Gonglja I think there should be a Sync button in your fork repository. Just click it.

**Pull request merged**
