### PR TITLE
feat: iteration & recursion in Zig

### PR DESCRIPTION
**Pull request by QiLOL**
This PR is intended to translate iteration & recursion functions to Zig. Please feel free let me know any update needed.

[Updated 10/01] adding missing part for time complexity.

If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by krahets** [comment]
Pending for reviewing by @sjinzh

**Review by sjinzh — CHANGES_REQUESTED** [review]
Please update build.zig.

**Comment by QiLOL** [comment]
> Please update build.zig.

Thanks for the reminder, updated. Please check.

**Review by krahets — APPROVED** [review]
Thanks for the PR! Look forward to your next contribution.

**Pull request merged**
