### PR TITLE
Add linked list structure definition C language code in "linked_list. md"

### PR DESCRIPTION
**Pull request by huawuque404**
If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [ ] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [ ] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [ ] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by krahets** [comment]
To be reviewed by @Reanon

**Comment by huawuque404** [comment]
OK

**Comment by Reanon** [comment]
The synchronization of C code to the document can be pended.

**Comment by huawuque404** [comment]
I'm a novice in an open source project. I don't quite understand what you mean. Can you explain it? Thank you.

**Review by krahets — APPROVED** [review]
Thanks @huawuque404.

The C codes will not be added to the docs before testing. But this definition is OK to be merged now.

**Comment by huawuque404** [comment]
Ok, I understand. Thank you very much.

**Pull request merged**
