### PR TITLE
translation: refine preface index and about_the_book (duplicates from #997)

### PR DESCRIPTION
**Pull request by yuelinxin**
This PR duplicates #997 , I addressed the suggestions mentioned in it. Apologies for this additional trouble.

### CODE REVIEW

**Comment by krahets** [comment]
Hi @yuelinxin , thanks for the PR! This section has some updates since the 1.0.0b6 version. Could you translate the latest document and merge your embellishments into it? Thanks!

**Comment by yuelinxin** [comment]
> Hi @yuelinxin , thanks for the PR! This section has some updates since the 1.0.0b6 version. Could you translate the latest document and merge your embellishments into it? Thanks!

Hmm, I compared the version you merged into my branch and the current Chinese version, I don't see any differences, did I miss something?

**Comment by krahets** [comment]
@yuelinxin I've updated the translation to the latest content. Could you add the modifications to it? Thx!

**Comment by yuelinxin** [comment]
> @yuelinxin Maybe your main branch has already been synchronized.
> 
> I've updated the translation with the latest content. Could you add the modifications to it? Thx!

done.

**Review by krahets — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
