### PR TITLE
add zig codes for Section 'Hash Map', 'Binary Tree' and 'Linear Search' 

### PR DESCRIPTION
**Pull request by sjinzh**
If this PR is related to coding or code translation, please fill out the checklist.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by sjinzh** [comment]
The output of "zig/chapter_hashing/hash_map.zig" as shown below,
未命名1673612669

**Comment by krahets** [comment]
Thanks for the PR. The output of the heap is not correct. It seems the problem of the tree printer. Please check it.

**Comment by sjinzh** [comment]
> Thanks for the PR. The output of the heap is not correct. It seems the problem of the tree printer. Please check it.

OK, the bug will be solved in next PR.
So, i delete the Section 'Heap' in this PR.

**Review by krahets — APPROVED** [review]
OK. Now merge it.

**Pull request merged**
