### PR TITLE
Modify the code style of C 

### PR DESCRIPTION
**Pull request by Reanon**
If this PR is related to coding or code translation, please fill out the checklist.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Review by krahets — APPROVED** [review]
Great changes! Thank you!

**Comment by krahets** [comment]
I'm wondering what is the usage of `uhash.h`?

**Comment by Reanon** [comment]
> I'm wondering what is the usage of `uhash.h`?

I don't know any more about `uhash.h` than you do.

**Comment by krahets** [comment]
> > I'm wondering what is the usage of `uhash.h`?
> 
> I don't know any more about `uhash.h` than you do.

Got it. I've removed it.

**Pull request merged**
