### PR TITLE
translation: Update chapter_graph/index.md

### PR DESCRIPTION
**Pull request by K3v123**
Just changed the words a little. honestly the Machine translation is good already.

If this pull request (PR) pertains to **Chinese-to-English translation**, please confirm that you have read the contribution guidelines and complete the checklist below:

- [x] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [x] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.

If this pull request (PR) is associated with **coding or code transpilation**, please attach the relevant console outputs to the PR and complete the following checklist:

- [ ] I have thoroughly reviewed the code, focusing on its formatting, comments, indentation, and file headers.
- [ ] I have confirmed that the code execution outputs are consistent with those produced by the reference code (Python or Java).
- [ ] The code is designed to be compatible on standard operating systems, including Windows, macOS, and Ubuntu.

### CODE REVIEW

**Review by magentaqin — CHANGES_REQUESTED** [review]
Suggest word changes from "every" to "each".

**Review by pengchzn — COMMENTED** [review]
I'm considering whether "vast" might be more appropriate, you can find an example in [The Times](https://www.collinsdictionary.com/dictionary/english/vast-database) stating, "They can search the vast database by age, by ability, by certain strengths." I think "database" aligns well with "network graph" in this context. It shows the extensive scope of the database, suggesting that "vast" aptly conveys the breadth and depth of the available resources.

**Comment by K3v123** [comment]
> I'm considering whether "vast" might be more appropriate, you can find an example in [The Times](https://www.collinsdictionary.com/dictionary/english/vast-database) stating, "They can search the vast database by age, by ability, by certain strengths." I think "database" aligns well with "network graph" in this context. It shows the extensive scope of the database, suggesting that "vast" aptly conveys the breadth and depth of the available resources.

Hi pengchzn
thanks for your comment! your right vast does make it a bit better. I'll change it back now.

**Review by pengchzn — APPROVED** [review]
That's ok~

**Review by magentaqin — APPROVED** [review]

**Review by krahets — APPROVED** [review]

**Pull request merged**
