### PR TITLE
Update stack.md

### PR DESCRIPTION
**Pull request by S-N-O-R-L-A-X**
add javascript and typescript for stack

### CODE REVIEW

**Review by yd-j — COMMENTED** [review]
A

**Review by krahets — COMMENTED** [review]
Thanks @S-N-O-R-L-A-X , Could you please add code files in `codes/javascript` , `codes/typescripts` ? You can refer to other languages such as Java, and C++.

**Comment by S-N-O-R-L-A-X** [comment]
> Thanks @S-N-O-R-L-A-X , Could you please add code files in `codes/javascript` , `codes/typescripts` ? You can refer to other languages such as Java, and C++.

Sorry, I have missed that before, now I have added the code in the folder.

**Review by krahets — APPROVED** [review]
Thanks @S-N-O-R-L-A-X for the clean code. Now merge it.

**Comment by krahets** [comment]
> > Thanks @S-N-O-R-L-A-X , Could you please add code files in `codes/javascript` , `codes/typescripts` ? You can refer to other languages such as Java, and C++.
> 
> Sorry, I have missed that before, now I have added the code in the folder.

The codes in the markdown and the source file are likely to be different as we add more `console.log()` in source files.

Please check the update at:

https://github.com/krahets/hello-algo/commit/3252b829e1ea3c40da3ed34c6dfb67436cbad3da#diff-bbdd9afdbb72803544a548dd519ae27e6117294bbacb1b2b954f3a58ad295629

**Comment by S-N-O-R-L-A-X** [comment]
> > > Thanks @S-N-O-R-L-A-X , Could you please add code files in `codes/javascript` , `codes/typescripts` ? You can refer to other languages such as Java, and C++.
> > 
> > 
> > Sorry, I have missed that before, now I have added the code in the folder.
> 
> The codes in the markdown and the source file are likely to be different as we add more `console.log()` in source files.
> 
> Please check the update at:
> 
> [3252b82#diff-bbdd9afdbb72803544a548dd519ae27e6117294bbacb1b2b954f3a58ad295629](https://github.com/krahets/hello-algo/commit/3252b829e1ea3c40da3ed34c6dfb67436cbad3da#diff-bbdd9afdbb72803544a548dd519ae27e6117294bbacb1b2b954f3a58ad295629)

Sorry for missing that! Need I complement it?

**Pull request merged**
