### PR TITLE
refactor: add/refactor method in include, simplified print code

### PR DESCRIPTION
**Pull request by hpstory**
If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

1. Change method signature from ArrToTree to ListToTree
2. Simplified code for print list
3. Use String alias
4. Change vertex val from property to field
5. Implement Print matrics with generic type
6. Method name in include use PascalCase

### CODE REVIEW

**Review by krahets — APPROVED** [review]
Thanks for the great changes!

**Comment by krahets** [comment]
Hi @hpstory! I found C# (or Microsoft) is the only language entering a new line before the open brace. It makes the codes too long to be shown compactly in the book.

We can modify the coding style by adding a `.editorconfig` file in the csharp folder. What do you think about the formatting styles? Is it acceptable?

```
# CSharp formatting rules
[*.cs]
csharp_new_line_before_open_brace = none
csharp_new_line_before_else = false
csharp_new_line_before_catch = false
csharp_new_line_before_finally = false
```

**Comment by hpstory** [comment]
> Hi @hpstory! I found C# (or Microsoft) is the only language entering a new line before the open brace. It makes the codes too long to be shown compactly in the book.
> 
> We can modify the coding style by adding a `.editorconfig` file in the csharp folder. What do you think about the formatting styles? Is it acceptable?
> 
> ```
> # CSharp formatting rules
> [*.cs]
> csharp_new_line_before_open_brace = none
> csharp_new_line_before_else = false
> csharp_new_line_before_catch = false
> csharp_new_line_before_finally = false
> ```

I think open brace will not affect reading. And editconfig will effective in new code, need to modify previous code use shortcuts `Ctrl+K+F`.

**Comment by krahets** [comment]
@hpstory I've reformatted the C# codes based on the modified rules. The shorter codes are cleaner to read in the book.

Please test the new code at https://github.com/krahets/hello-algo/commit/73dcb4cea934d6d1848ce8d475cd69730693bce7 if you are available.

**Comment by hpstory** [comment]
@krahets All test cases output normally.

Screenshot 2023-04-23 095428

**Comment by krahets** [comment]
@hpstory Thanks!

**Pull request merged**
