### PR TITLE
feat: add Swift codes for graph_operations article

### PR DESCRIPTION
**Pull request by nuomi1**
If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by nuomi1** [comment]
```text
result of `graph_adjacency_matrix.swift`


初始化后，图为
顶点列表 = [1, 3, 2, 5, 4]
邻接矩阵 =
[
  [0, 1, 1, 1, 0],
  [1, 0, 1, 0, 0],
  [1, 1, 0, 1, 1],
  [1, 0, 1, 0, 1],
  [0, 0, 1, 1, 0],
]

添加边 1-2 后，图为
顶点列表 = [1, 3, 2, 5, 4]
邻接矩阵 =
[
  [0, 1, 1, 1, 0],
  [1, 0, 1, 0, 0],
  [1, 1, 0, 1, 1],
  [1, 0, 1, 0, 1],
  [0, 0, 1, 1, 0],
]

删除边 1-3 后，图为
顶点列表 = [1, 3, 2, 5, 4]
邻接矩阵 =
[
  [0, 0, 1, 1, 0],
  [0, 0, 1, 0, 0],
  [1, 1, 0, 1, 1],
  [1, 0, 1, 0, 1],
  [0, 0, 1, 1, 0],
]

添加顶点 6 后，图为
顶点列表 = [1, 3, 2, 5, 4, 6]
邻接矩阵 =
[
  [0, 0, 1, 1, 0, 0],
  [0, 0, 1, 0, 0, 0],
  [1, 1, 0, 1, 1, 0],
  [1, 0, 1, 0, 1, 0],
  [0, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 0],
]

删除顶点 3 后，图为
顶点列表 = [1, 2, 5, 4, 6]
邻接矩阵 =
[
  [0, 1, 1, 0, 0],
  [1, 0, 1, 1, 0],
  [1, 1, 0, 1, 0],
  [0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0],
]
```

```text
result of `graph_adjacency_list.swift`


初始化后，图为
邻接表 =
2: [5, 3, 4],
1: [3, 5],
5: [2, 1, 4],
3: [1, 2],
4: [2, 5],

添加边 1-2 后，图为
邻接表 =
2: [5, 3, 4, 1],
1: [3, 5, 2],
5: [2, 1, 4],
3: [1, 2],
4: [2, 5],

删除边 1-3 后，图为
邻接表 =
2: [5, 3, 4, 1],
1: [5, 2],
5: [2, 1, 4],
3: [2],
4: [2, 5],

添加顶点 6 后，图为
邻接表 =
2: [5, 3, 4, 1],
1: [5, 2],
5: [2, 1, 4],
6: [],
3: [2],
4: [2, 5],

删除顶点 3 后，图为
邻接表 =
2: [5, 4, 1],
1: [5, 2],
5: [2, 1, 4],
6: [],
4: [2, 5],
```

**Review by krahets — APPROVED** [review]
Thanks for the clean codes!

**Comment by krahets** [comment]
Hi @nuomi1 ! Would you like to be the reviewer for Swift?

image

I'll mention you in the PRs related to Swift. You can comment in the PR. Once you approve it, I'll merge it.

And I plan to add a "Acknowledgements" block to the HelloAlgo site.

**Comment by nuomi1** [comment]
> Hi @nuomi1 ! Would you like to be the reviewer for Swift?
> 
> image
> 
> I'll mention you in the PRs related to Swift. You can comment in the PR. Once you approve it, I'll merge it.
> 
> And I plan to add a "Acknowledgements" block to the HelloAlgo site.

OK.

**Pull request merged**
