### PR TITLE
Finalize Ruby code transpilation

### PR DESCRIPTION
**Pull request by khoaxuantu**
If this pull request (PR) is associated with **coding or code transpilation**, please attach the relevant console outputs to the PR and complete the following checklist:

- [x] I have thoroughly reviewed the code, focusing on its formatting, comments, indentation, and file headers.
- [x] I have confirmed that the code execution outputs are consistent with those produced by the reference code (Python or Java).
- [x] The code is designed to be compatible on standard operating systems, including Windows, macOS, and Ubuntu.

---

I have checked all the topics again and seen that we have done the Ruby code transpilation :partying_face: 
Here is the finalized PR for Ruby.

### CODE REVIEW

**Review by krahets — APPROVED** [review]
Thanks @khoaxuantu ! Cheers :beers: !

**Comment by krahets** [comment]
@khoaxuantu I've added your GitHub username to https://www.hello-algo.com/ . Please let me know if there is any mistake.

**Comment by khoaxuantu** [comment]
> @khoaxuantu I've added your GitHub username to https://www.hello-algo.com/ . Please let me know if there is any mistake.

It's all good! Can't wait to see myself in `en` and `zh-TW` sites later on 🎉

**Comment by krahets** [comment]
@khoaxuantu Sure. I'll handle it.

**Pull request merged**
