### PR TITLE
docs(array.md): Added go array initialization code example

### PR DESCRIPTION
**Pull request by guowei-gong**
If this PR is related to coding or code translation, please fill out the checklist.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Sorry that I can't merge this PR because of the requirement of finishing at least one markdown file.

**Comment by guowei-gong** [comment]
> Sorry that I can't merge this PR because of the requirement of finishing at least one markdown file.

fine

**Comment by guowei-gong** [comment]
> Sorry that I can't merge this PR because of the requirement of finishing at least one markdown file.

I completed the golang code required in this module.

**Comment by guowei-gong** [comment]
@krahets

**Review by krahets — COMMENTED** [review]
Please create `array.go` source code file.

**Pull request closed without merging**
