### PR TITLE
feat: add Swift codes for queue article

### PR DESCRIPTION
**Pull request by nuomi1**
If this PR is related to coding or code translation, please fill out the checklist.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by nuomi1** [comment]
```text
result of `queue.swift`

队列 queue = [1, 3, 2, 5, 4]
队首元素 peek = 1
出队元素 poll = 1，出队后 queue = [3, 2, 5, 4]
队列长度 size = 4
队列是否为空 = false
```

```text
result of `linkedlist_queue.swift`

队列 queue = [1, 3, 2, 5, 4]
队首元素 peek = 1
出队元素 poll = 1，出队后 queue = [3, 2, 5, 4]
队列长度 size = 4
队列是否为空 = false
```

```text
result of `array_queue.swift`

队列 queue = [1, 3, 2, 5, 4]
队首元素 peek = 1
队列 queue = [1, 3, 2, 5, 4]
队首元素 peek = 1
队列 queue = [1, 3, 2, 5, 4]
队首元素 peek = 1
出队元素 poll = 1，出队后 queue = [3, 2, 5, 4]
队列长度 size = 4
队列是否为空 = false
第 0 轮入队 + 出队后 queue = [2, 5, 4, 0]
第 1 轮入队 + 出队后 queue = [5, 4, 0, 1]
第 2 轮入队 + 出队后 queue = [4, 0, 1, 2]
第 3 轮入队 + 出队后 queue = [0, 1, 2, 3]
第 4 轮入队 + 出队后 queue = [1, 2, 3, 4]
第 5 轮入队 + 出队后 queue = [2, 3, 4, 5]
第 6 轮入队 + 出队后 queue = [3, 4, 5, 6]
第 7 轮入队 + 出队后 queue = [4, 5, 6, 7]
第 8 轮入队 + 出队后 queue = [5, 6, 7, 8]
第 9 轮入队 + 出队后 queue = [6, 7, 8, 9]
```

**Review by krahets — COMMENTED** [review]
Thanks! The output of `array_queue` shown in this PR is not consistent with other languages. Please check it.

**Comment by nuomi1** [comment]
@krahets It's just the console output error.

**Review by krahets — APPROVED** [review]
Thanks! Now merge it.

**Pull request merged**
