### PR TITLE
列表章节中,C语言实现列表打印时有误,故作此修改!

### PR DESCRIPTION
**Pull request by Xi-Row**
If this pull request (PR) pertains to **Chinese-to-English translation**, please confirm that you have read the contribution guidelines and complete the checklist below:

- [ ] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [ ] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.

If this pull request (PR) is associated with **coding or code transpilation**, please attach the relevant console outputs to the PR and complete the following checklist:

- [ ] I have thoroughly reviewed the code, focusing on its formatting, comments, indentation, and file headers.
- [ ] I have confirmed that the code execution outputs are consistent with those produced by the reference code (Python or Java).
- [ ] The code is designed to be compatible on standard operating systems, including Windows, macOS, and Ubuntu.

### CODE REVIEW

**Comment by krahets** [comment]
Hi，请附上测试结果，说明哪里有误，thx

**Comment by Xi-Row** [comment]
> Hi，请附上测试结果，说明哪里有误，thx

我应该附在哪里啊，评论下面还是pull request 中的文件里

**Comment by krahets** [comment]
附在评论里就好

**Comment by Xi-Row** [comment]
> 附在评论里就好

[修改说明.md](https://github.com/user-attachments/files/17919283/default.md)

**Comment by Xi-Row** [comment]
你好，我想知道我的拉取请求哪里有误吗，或者为什么没有通过请求（哭）

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Yudong Jin ***@***.***>
发送时间: Tuesday, November 26, 2024 5:02:07 PM
收件人: krahets/hello-algo ***@***.***>
抄送: pzpz ***@***.***>; Comment ***@***.***>
主题: Re: [krahets/hello-algo] 列表章节中,C语言实现列表打印时有误,故作此修改! (PR #1571)


附在评论里就好

―

**Pull request closed without merging**
