### PR TITLE
Update time_complexity.md

### PR DESCRIPTION
**Pull request by mellowrsa**
If this PR is related to coding or code translation, please fill out the checklist.

- [√] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [√] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [√] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Thanks for the fix! Could you update the source code file (in `codes/c/...`) as well?

**Comment by mellowrsa** [comment]
> Thanks for the fix! Could you update the source code file (in `codes/c/...`) as well?

OK，I found that the code in bubble_sort.c is correct

**Comment by sjinzh** [comment]
@mellowrsa @krahets Thanks! The bug in source code is fixed in PR #228.

**Review by krahets — APPROVED** [review]
Thanks!

**Pull request merged**
