### PR TITLE
Suggestion on merge_sort.md

### PR DESCRIPTION
**Pull request by GN-Yu**
修改了代码注释使其表述更严谨，如C++中：

for (int k = left; k <= right; k++) {
            // 若“左子数组已全部合并完”，则选取右子数组元素，并且 j++
            if (i > leftEnd)
                nums[k] = tmp[j++];
            // 否则，若“右子数组已全部合并完”或“左子数组元素 <ins> <= </ins> 右子数组元素”，则选取左子数组元素，并且 i++
            else if (j > rightEnd || tmp[i] <= tmp[j])
                nums[k] = tmp[i++];
            // 否则，若<ins>“左右子数组都未全部合并完”且“左子数组元素 > 右子数组元素”</ins>，则选取右子数组元素，并且 j++
            else
                nums[k] = tmp[j++];
        }

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
LGTM! Could you help modify the comments in all the source codes as well? Thanks.

**Comment by GN-Yu** [comment]
> LGTM! Could you help modify the comments in all the source codes as well? Thanks.

The midifications were applied to all source codes, not just C++. :)

Thanks for the nice book. Look forward to more updates!

**Comment by krahets** [comment]
> The midifications were applied to all source codes, not just C++. :)
> 
> Thanks for the nice book. Look forward to more updates!

Thanks! I meant modifying the comments of the source codes in the `codes` directory.

**Comment by mrxiaojie** [comment]
早上好！您的邮件我已经收到了，谢谢您的支持！

**Review by krahets — APPROVED** [review]

**Pull request merged**
