### PR TITLE
Feature/chapter dynamic programming swift

### PR DESCRIPTION
**Pull request by nuomi1**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by nuomi1** [comment]
```text
result of `climbing_stairs_backtrack.swift`

爬 9 阶楼梯共有 55 种方案
```

```text
result of `climbing_stairs_dfs.swift`

爬 9 阶楼梯共有 55 种方案
```

```text
result of `climbing_stairs_dfs_mem.swift`

爬 9 阶楼梯共有 55 种方案
```

```text
result of `climbing_stairs_dp.swift`

爬 9 阶楼梯共有 55 种方案
爬 9 阶楼梯共有 55 种方案
```

**Comment by nuomi1** [comment]
```text
result of `min_cost_climbing_stairs_dp.swift`

输入楼梯的代价列表为 [0, 1, 10, 1, 1, 1, 10, 1, 1, 10, 1]
爬完楼梯的最低代价为 6
爬完楼梯的最低代价为 6
```

```text
result of `climbing_stairs_constraint_dp.swift`

爬 9 阶楼梯共有 9 种方案
```

**Comment by nuomi1** [comment]
```text
result of `min_path_sum.swift`

从左上角到右下角的做小路径和为 13
从左上角到右下角的做小路径和为 13
从左上角到右下角的做小路径和为 13
从左上角到右下角的做小路径和为 13
```

**Comment by nuomi1** [comment]
```text
result of `knapsack.swift`

不超过背包容量的最大物品价值为 270
不超过背包容量的最大物品价值为 270
不超过背包容量的最大物品价值为 270
不超过背包容量的最大物品价值为 270
```

**Comment by nuomi1** [comment]
```text
result of `unbounded_knapsack.swift`

不超过背包容量的最大物品价值为 22
不超过背包容量的最大物品价值为 22
```

```text
result of `coin_change.swift`

凑到目标金额所需的最少硬币数量为 2
凑到目标金额所需的最少硬币数量为 2
```

```text
result of `coin_change_ii.swift`

凑出目标金额的硬币组合数量为 4
凑出目标金额的硬币组合数量为 4
```

**Comment by nuomi1** [comment]
```text
result of `edit_distance.swift`

将 bag 更改为 pack 最少需要编辑 3 步
将 bag 更改为 pack 最少需要编辑 3 步
将 bag 更改为 pack 最少需要编辑 3 步
将 bag 更改为 pack 最少需要编辑 3 步
```

**Review by krahets — APPROVED** [review]
Thanks for the clean code!

**Pull request merged**
