### PR TITLE
restructure rust code, using library way, not include

### PR DESCRIPTION
**Pull request by rongyi**
I hurts me everytime when I see include in rust, time to fix this.

### CODE REVIEW

**Review by krahets — APPROVED** [review]
Great updates! Thank you!

**Comment by krahets** [comment]
Hi @rongyi, I’d like to invite you to be a code reviewer for our project. We’ll also thank you on the landing page for your contribution. Please let me know if you’re interested in joining.

**Comment by rongyi** [comment]
@krahets I’m honored to be a reviewer for your remarkable project. I look forward to contributing valuable insights and feedback to help ensure its success.

**Comment by krahets** [comment]
@rongyi Please add my WeChat `krahets-jyd` if you're convenient. I'll invite you to the reviewers' group chat.

**Pull request merged**
