### PR TITLE
feat(csharp): add csharp code for charper dynamic programming

### PR DESCRIPTION
**Pull request by hpstory**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

Test result:

### CODE REVIEW

**Comment by krahets** [comment]
So timely!

I have added new codes for this section. Could u please update the C# code too?

See https://github.com/krahets/hello-algo/commit/920512d87221b68876c682a169f801e120fca329

**Comment by krahets** [comment]
Hi @hpstory, would you like to work with us as the reviewer of C# of this project?

1. You'll get notifications for the updates on wechat.
2. All the C# PR will be assigned to you for reviewing.
3. Your GitHub ID will be listed on the [landing page](www.hello.com).

**Comment by hpstory** [comment]
> So timely!
> 
> I have added new codes for this section. Could u please update the C# code too?
> 
> See [920512d](https://github.com/krahets/hello-algo/commit/920512d87221b68876c682a169f801e120fca329)

Done

**Comment by hpstory** [comment]
> Hi @hpstory, would you like to work with us as the reviewer of C# of this project?
> 
> 1. You'll get notifications for the updates on wechat.
> 2. All the C# PR will be assigned to you for reviewing.
> 3. Your GitHub ID will be listed on the landing page ([www.hello-algo.com](http://www.hello-algo.com)).

Thanks for your inviting. I am happy to look forward to working with you and the team.

**Review by krahets — APPROVED** [review]
Thanks @hpstory ! Welcome onboard!

**Comment by krahets** [comment]
@hpstory Please add my wechat krahet-jyd, thx!

**Comment by hpstory** [comment]
> @hpstory Please add my wechat krahet-jyd, thx!

@krahets Sorry, I didn't find you through account on WeChat. So I sent my phone number to your 163 email(krahets@163.com), perhaps you can check on it

**Pull request merged**
