### PR TITLE
Update hashing_search.md

### PR DESCRIPTION
**Pull request by zhuoqinyue**
补充js和ts对应的哈希查找

If this PR is related to coding or code translation, please fill out the checklist.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Thanks! Could you create source code files?

**Comment by zhuoqinyue** [comment]
> Thanks! Could you create source code files?

What should I do? 
I mean how should I send you the source file
By commit?

**Comment by krahets** [comment]
All the source codes are available at `codes/javascript` and `codes/typescript`.
You should create a file there and commit+push it.

**Comment by zhuoqinyue** [comment]
I probably get it.
One more question! In your code style, which one should I use, if or ternary expression?

**Comment by krahets** [comment]
Both are fine for me~

**Comment by zhuoqinyue** [comment]
hey, i open a new PR #187 . You can close this PR

**Pull request closed without merging**
