### PR TITLE
rust and zig : add codes for chapter_dynamic_programming

### PR DESCRIPTION
**Pull request by sjinzh**
@krahets  Hi,
- commit 1 => rust : add codes for chapter_dynamic_programming.
- commit 2 => zig : add codes for chapter_dynamic_programming.
- commit 3 => rust : add codes for chapter_backtracking.

If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Awesome! Thank you @sjinzh.

Have you test the code and  check all the output to the reference language(Python or Java) ?

**Comment by sjinzh** [comment]
> Awesome! Thank you @sjinzh.
> 
> Have you test the code and check all the output to the reference language(Python or Java) ?

@krahets  Yes, all the codes outpus are the same with Java codes.

**Review by krahets — APPROVED** [review]
Thanks for the clean codes!

**Comment by krahets** [comment]
Hi @sjinzh, I found that the Zig code of this PR used the underscore naming style, which should be the camel naming style. Please fix it thx.

**Pull request merged**
