### PR TITLE
fix: Removed unnecessary JS codes in linked_list.md

### PR DESCRIPTION
**Pull request by logan-qiu**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by logan-qiu** [comment]
@krahets k神，我认为实际操作中JS只需要以这样的写法就可以了：
image
按照修改后的理解可能会更加直观

**Review by justin-tse — COMMENTED** [review]
@logan-qiu Thank you! I agree that removing it will be better for JS in this place. But this is also a correct way to define a class, making it more documented. This is called field declarations. You can see some reference from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)
image

**Comment by krahets** [comment]
LeetCode also uses the simplified definition. Do you think it is better to merge this PR @justin-tse ?

```
/**
 * Definition for singly-linked list.
 * function ListNode(val, next) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.next = (next===undefined ? null : next)
 * }
 */
```

**Comment by logan-qiu** [comment]
@justin-tse Hey Justin, thank you for the reference!

I understand the original purpose to declare fields up-front would help with optimization, but I believe this is not a common approach in a real-world scenario. Also it is slightly less readable.

image

Maybe we can do an optional page with introducing private class features? Just an idea, we can definitely go with the existing one but personally I like it to be simpler and more readable.

**Comment by justin-tse** [comment]
@logan-qiu @krahets Thank you! I also prefer the simplified definition.

**Comment by justin-tse** [comment]
@logan-qiu Could you help to update the Javascript code for this not-common style?

**Comment by logan-qiu** [comment]
@justin-tse May I also make adjustments with other code blocks with field declarations and re-submit the PR?

**Comment by justin-tse** [comment]
@logan-qiu Thank you, please do that.

**Comment by krahets** [comment]
@logan-qiu It is more convenient to add commits to your forked repo, which will be synchronized to this PR automatically.

**Pull request closed without merging**
