### PR TITLE
translation: Update the mindmap

### PR DESCRIPTION
**Pull request by krahets**
If this pull request (PR) pertains to **Chinese-to-English translation**, please confirm that you have read the contribution guidelines and complete the checklist below:

- [x] This PR represents the translation of a single, complete document, or contains only bug fixes.
- [x] The translation accurately conveys the original meaning and intent of the Chinese version. If deviations exist, I have provided explanatory comments to clarify the reasons.

### CODE REVIEW

**Comment by krahets** [comment]
The Chinese version is:
hello_algo_mindmap

**Review by RafaelCaso — APPROVED** [review]
Looks good. As we discussed, I suggested Capitalizing the root nodes (Data structures -> Data Structures etc.) and it was decided that we would follow the example of Wikipedia's style guide where they only capitalize the first letter.

**Comment by krahets** [comment]
> Looks good. As we discussed, I suggested Capitalizing the root nodes (Data structures -> Data Structures etc.) and it was decided that we would follow the example of Wikipedia's style guide where they only capitalize the first letter.

Thanks, @RafaelCaso! I'll unify the headings' format via a new PR and mention you there.

**Comment by thomasq0** [comment]
We have `Data structures` and `Data structure` and it confused me the difference between the two. I guess the `Data structure` means "Data representation and storage", which is the foundation of "Data structures". It is probably not translation issue as they are exact same in Chinese version.

**Comment by thomasq0** [comment]
The last branch of topic "Hash table" sees "Design principle of hash algorithm". The Chinese version means "Hash algorithm's use cases and design goals".

**Comment by thomasq0** [comment]
The second branch of "Tree" can be "Linked list representation vs array representation". And do we want to mention different types of `tree` as "trees"?

**Comment by thomasq0** [comment]
In "Graph", "Adjacency list vs adjacency matric".

**Comment by thomasq0** [comment]
"Characteristics, Identification" in "Divide and conquer" failed to deliver the exact meaning in Chinese version. How about "Identify use cases by exhibiting characteristics"?

**Comment by thomasq0** [comment]
In "Backtracking", "Framework code" might mean "Code Pattern"?

**Comment by krahets** [comment]
> We have `Data structures` and `Data structure` and it confused me the difference between the two. I guess the `Data structure` means "Data representation and storage", which is the foundation of "Data structures". It is probably not translation issue as they are exact same in Chinese version.

They are the same. I'll unify them

**Comment by krahets** [comment]
> The last branch of topic "Hash table" sees "Design principle of hash algorithm". The Chinese version means "Hash algorithm's use cases and design goals".

Fixed

**Comment by krahets** [comment]
> In "Graph", "Adjacency list vs adjacency matric".

Done

**Comment by krahets** [comment]
> The second branch of "Tree" can be "Linked list representation vs array representation". And do we want to mention different types of `tree` as "trees"?

Done. 
Do you mean using "Binary search tree" instead of "Binary search trees"? I think so.

**Comment by krahets** [comment]
> "Characteristics, Identification" in "Divide and conquer" failed to deliver the exact meaning in Chinese version. How about "Identify use cases by exhibiting characteristics"?

The Chinese version "分治问题特性、判断方法" has two terms: characteristics, methods to identify the problem. 

How about "Characteristics, Identification methods of the problems"?

**Comment by thomasq0** [comment]
> > "Characteristics, Identification" in "Divide and conquer" failed to deliver the exact meaning in Chinese version. How about "Identify use cases by exhibiting characteristics"?
> 
> The Chinese version "分治问题特性、判断方法" has two terms: characteristics, methods to identify the problem.
> 
> "Identify use cases by exhibiting characteristics" is great but it's so long that it doesn't fit on one line. How about "Characteristics, Identification methods of the problems"?

How about simply "Identify the problem"? Here, we are talking about the key points which don't have to be a noun or noun phrase.

**Comment by thomasq0** [comment]
> > The second branch of "Tree" can be "Linked list representation vs array representation". And do we want to mention different types of `tree` as "trees"?
> 
> Done. Do you mean using "Binary search tree" instead of "Binary search trees"? I think so.

Yes, **tree** is an abstract concept here.

**Comment by krahets** [comment]
> > > The second branch of "Tree" can be "Linked list representation vs array representation". And do we want to mention different types of `tree` as "trees"?
> > 
> > 
> > Done. Do you mean using "Binary search tree" instead of "Binary search trees"? I think so.
> 
> Yes, **tree** is an abstract concept here.

Fixed

**Comment by krahets** [comment]
> > > "Characteristics, Identification" in "Divide and conquer" failed to deliver the exact meaning in Chinese version. How about "Identify use cases by exhibiting characteristics"?
> > 
> > 
> > The Chinese version "分治问题特性、判断方法" has two terms: characteristics, methods to identify the problem.
> > "Identify use cases by exhibiting characteristics" is great but it's so long that it doesn't fit on one line. How about "Characteristics, Identification methods of the problems"?
> 
> How about simply "Identify the problem"? Here, we are talking about the key points which don't have to be a noun or noun phrase.
Sure. I updated it to "characteristics, identify the problem". Plz let me know if I made mistakes.

**Comment by krahets** [comment]
@thomasq0 Please check the latest updates. Thx!

**Review by thomasq0 — APPROVED** [review]
Approved

**Review by thomasq0 — APPROVED** [review]

**Comment by krahets** [comment]
Thanks for your review @thomasq0 @RafaelCaso !

**Pull request merged**
