### PR TITLE
add zig code for chapter_computational_complexity (Zig Version 0.10.0)

### PR DESCRIPTION
**Pull request by sjinzh**
If this PR is related to coding or code translation, please fill out the checklist.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Thanks for the clean code!

Could you paste the output of the code to this PR? Because I don't write Zig and can not run it.

**Comment by sjinzh** [comment]
> Thanks for the clean code!
> 
> Could you paste the output of the code to this PR? Because I don't write Zig and can not run it.

No problem!
The output of time_complexity.zig as shown below.
time_complexity
The output of worst_best_time_complexity.zig as shown below.
worst_best_time_complexity

**Review by krahets — APPROVED** [review]
Thanks, @sjinzh! I'm wondering if you will continue to add the zig codes because it is difficult to find other zig coders.

**Comment by sjinzh** [comment]
> Thanks, @sjinzh! I'm wondering if you will continue to add the zig codes because it is difficult to find other zig coders.

Yes, i will.

**Pull request merged**
