### PR TITLE
Update array.md

### PR DESCRIPTION
**Pull request by Javesun99**
数组插入应该取不到索引值才对

> Tip: If this PR is not related to the coding or code translation, please ignore the checklist.

### Checklist

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code is not relied on a particular environment or IDE and can be runned on a common system (Win, MacOS, Ubuntu).

### CODE REVIEW

**Comment by krahets** [comment]
Thanks! Has the code been tested? Please show the output of the test case.

**Comment by Javesun99** [comment]
> 
image
结果一样 但是教程上的代码会多跑一步

**Review by jch12138 — COMMENTED** [review]
replace >= with > can reduce operation times and prevent the index out of range error when insert number to index 0.

**Review by krahets — APPROVED** [review]
Great correction. Thanks!

**Pull request merged**
