### PR TITLE
fix: 二分查找，左闭右开区间实现中，注释区间范围右侧符号应该是)而不应该是]

### PR DESCRIPTION
**Pull request by FangYuan33**
我觉得需要改一下，这样更好理解

### CODE REVIEW

**Review by krahets — COMMENTED** [review]
Thanks for the fix! Could you help update the comments in the source code files as well?

**Comment by FangYuan33** [comment]
> Thanks for the fix! Could you help update the comments in the source code files as well?

ok! my pleasure. when fixing it, I lost code need...

**Comment by FangYuan33** [comment]
> Thanks for the fix! Could you help update the comments in the source code files as well?

Only TypeScript is wrong, others is right.

**Review by krahets — APPROVED** [review]
Great! Now merge it.

**Pull request merged**
