### PR TITLE
translation: Update chapter_array_and_linkedlist/summary.md

### PR DESCRIPTION
**Pull request by K3v123**
changed some words to make it more consistent to the changed mds.

If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [ ] I've tested the code and ensured the outputs are the same as the outputs of reference code.
- [ ] I've checked the code (formatting, comments, indentation, file header, etc) carefully.
- [ ] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by K3v123** [comment]
the
"!!! question "After deleting a node, is it necessary to set `P.next` to `None`?""
the none can be changed to null.... but none should still be correct if its in Python, so I did not change it to null. Should I change it or its fine?

**Comment by krahets** [comment]
@K3v123 Hi, it has been clarified in 0.2.1:

> When it comes to terms that are inconsistent between programming languages, this book follows Python, for example using None to mean "empty".

We use `None` to represent null throughout the book.

**Review by yuelinxin — APPROVED** [review]
Looks good to me. Thanks for the PR!

**Comment by yuelinxin** [comment]
Hi @krahets , I think this PR should be the `summary.md` of chapter array and linked list. I'm currently working on the summary for chapter data structure.

**Comment by krahets** [comment]
@yuelinxin Fixed it. Thx!

**Review by QiLOL — APPROVED** [review]
@K3v123  Thanks for the contribution, looks good to me!

**Review by krahets — APPROVED** [review]

**Pull request merged**
