### PR TITLE
feature: add auto-build-and-test workflow for go

### PR DESCRIPTION
**Pull request by hpstory**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference code.
- [x] I've checked the code (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by hpstory** [comment]
The code in this PR was generated and modified by GPT. I tested it in my own forked repo and found the following issues that need help.

**Comment by hpstory** [comment]
- [ ] Go code get unexpected result when testing TestSpaceComplexity, [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382184822/job/20081646864), log:

**Comment by hpstory** [comment]
- [ ] JS/TS may need a package.json file to test codes, I just create an empty package.json file in [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382185109/job/20081648157)

**Comment by hpstory** [comment]
- [ ] Zig codes got compile errors, I'm not sure if it's a syntax error or if the wrong sdk version(0.11.0) was used. [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382185433/job/20081648858), log:

**Comment by krahets** [comment]
Thanks for the PR! 

@Reanon @justin-tse @codingonion 
Please help @hpstory  test the workflow when you’re convenient, thanks!

**Comment by hpstory** [comment]
Also fix Python Unicode Decode Error on Windows.
Before: [workflow](https://github.com/krahets/hello-algo/actions/runs/7346560815/job/20001537089) 

After: [workflow](https://github.com/krahets/hello-algo/actions/runs/7383496270/job/20084799991)

**Comment by krahets** [comment]
@hpstory Thanks for checking the testing result! The bug has been fixed.

```shell
=== RUN   TestSpaceComplexity
递归 n = 5
递归 n = 4
递归 n = 3
递归 n = 2
递归 n = 1
递归 n = 5 中的 nums 长度 = 5
递归 n = 4 中的 nums 长度 = 4
递归 n = 3 中的 nums 长度 = 3
递归 n = 2 中的 nums 长度 = 2
递归 n = 1 中的 nums 长度 = 1
                /———0
            /———0
           |    \———0
        /———0
       |   |    /———0
       |    \———0
       |        \———0
    /———0
   |   |        /———0
   |   |    /———0
   |   |   |    \———0
   |    \———0
   |       |    /———0
   |        \———0
   |            \———0
———0
   |            /———0
   |        /———0
   |       |    \———0
   |    /———0
   |   |   |    /———0
   |   |    \———0
   |   |        \———0
    \———0
       |        /———0
       |    /———0
       |   |    \———0
        \———0
           |    /———0
            \———0
                \———0
--- PASS: TestSpaceComplexity (0.00s)
PASS
ok      github.com/krahets/hello-algo/chapter_computational_complexity  0.520s
```

**Comment by krahets** [comment]
> * [ ]  Zig codes got compile errors, I'm not sure if it's a syntax error or if the wrong sdk version(0.11.0) was used. [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382185433/job/20081648858), log:
>   

I would recommend merge the workflow file of Go and JS/TS. They seem to be working fine.

Have you tried adding a bug to Go/JS/TS code to see if the workflow can report it?

**Comment by hpstory** [comment]
> > * [ ]   Zig codes got compile errors, I'm not sure if it's a syntax error or if the wrong sdk version(0.11.0) was used. [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382185433/job/20081648858), log:
> >   
> 
> I would recommend merging the workflow file of Go and JS/TS first. They seem to be working fine.
> 
> Have you tried adding a bug to Go/JS/TS code to see if the workflow can report it?

No problem with Go. but JS and TS workflow actually did nothing, we need two scripts for build and test.
Capture

**Comment by krahets** [comment]
> > > * [ ]    Zig codes got compile errors, I'm not sure if it's a syntax error or if the wrong sdk version(0.11.0) was used. [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382185433/job/20081648858), log:
> > >   
> > 
> > 
> > I would recommend merging the workflow file of Go and JS/TS first. They seem to be working fine.
> > Have you tried adding a bug to Go/JS/TS code to see if the workflow can report it?
> 
> No problem with Go. but JS and TS workflow actually did nothing, we need two scripts for build and test. Capture

I suggest merging the workflow of Go first. Let's open two new PRs for the JS/TS, Zig's workflow.

**Comment by hpstory** [comment]
> > > > * [ ]     Zig codes got compile errors, I'm not sure if it's a syntax error or if the wrong sdk version(0.11.0) was used. [workflow](https://github.com/hpstory/hello-algo/actions/runs/7382185433/job/20081648858), log:
> > > >   
> > > 
> > > 
> > > I would recommend merging the workflow file of Go and JS/TS first. They seem to be working fine.
> > > Have you tried adding a bug to Go/JS/TS code to see if the workflow can report it?
> > 
> > 
> > No problem with Go. but JS and TS workflow actually did nothing, we need two scripts for build and test. Capture
> 
> I suggest merging the workflow of Go first. Let's open two new PRs for the JS/TS, Zig's workflow.

Done

**Review by krahets — APPROVED** [review]
Thanks to @hpstory for the PR!

**Pull request merged**
