### PR TITLE
Update classification_of_data_structure.md

### PR DESCRIPTION
**Pull request by Phoenix0415**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [ ] I've tested the code and ensured the outputs are the same as the outputs of reference code.
- [ ] I've checked the code (formatting, comments, indentation, file header, etc) carefully.
- [ ] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by yuelinxin** [comment]
Hi there, than you for your PR.  This PR is duplicate with #1005, can you check if it has the same changes, if not we can merge your PR after #1005.

**Comment by Phoenix0415** [comment]
hi, Thank you for your feedback. I added the term "层级结构" to provide a more detailed description.

here's what changed in my PR:
"树形结构和网状结构" -> "树形结构(或层级结构)和网状结构"

#1005
"divided into tree structures and network structures"

I recommend merging my PR after #1005 if the changes are acceptable

**Comment by krahets** [comment]
Hi @Phoenix0415 , thanks for your PR!

树形结构 and 层级结构 are not equavilant. 层级结构 is more general than 树形结构. Specifically, in 层级结构, it is not required that each child-node should correspond to only one parent-node.

**Comment by Phoenix0415** [comment]
uh, I see.
thanks for your explanation and clarification!

**Pull request closed without merging**
