### PR TITLE
update rust codes for hash_map, binary_search, bubble_sort, stack, queue

### PR DESCRIPTION
**Pull request by sjinzh**
If this PR is related to coding or code translation, please read the [contribution guideline](https://github.com/krahets/hello-algo/issues/15#issue-1464069591), fill out the checklist, and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
- [x] The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

### CODE REVIEW

**Comment by sjinzh** [comment]
The output of "codes/rust/chapter_computational_complexity/time_complexity.rs" is shown below,
time_complexity

The output of "codes/rust/chapter_computational_complexity/worst_best_time_complexity.rs" is shown below,
worst_best_time_complexity

The output of "codes/rust/chapter_computational_complexity/leetcode_two_sum.rs" is shown below,
leetcode_two_sum

The output of "codes/rust/chapter_array_and_linkedlist/array.rs" is shown below,
array

The output of "codes/rust/chapter_array_and_linkedlist/list.rs" is shown below,
list

The output of "codes/rust/chapter_stack_and_queue/stack.rs" is shown below,
stack

The output of "codes/rust/chapter_stack_and_queue/queue.rs" is shown below,
queue

The output of "codes/rust/chapter_stack_and_queue/deque.rs" is shown below,
deque

The output of "codes/rust/chapter_hashing/hash_map.rs" is shown below,
hash_map

The output of "codes/rust/chapter_searching/binary_search.rs" is shown below,
binary_search

The output of "codes/rust/chapter_sorting/bubble_sort.rs" is shown below,
bubble_sort

**Review by krahets — APPROVED** [review]
Awesome! Thanks, @sjinzh !

**Comment by krahets** [comment]
Hi @sjinzh! Would you like to be the reviewer for Zig and Rust?

**Comment by sjinzh** [comment]
> Hi @sjinzh! Would you like to be the reviewer for Zig and Rust?

@krahets  Sure I would. It's my honour. Thanks!

**Comment by krahets** [comment]
> > Hi @sjinzh! Would you like to be the reviewer for Zig and Rust?
> 
> @krahets Sure I would. It's my honour. Thanks!

Great! I'll mention you in the PRs related to Zig and Rust. You can comment in the PR. Once you approve it, I'll merge it.

And I plan to add a "Acknowledgements" block to the HelloAlgo site.

Thank you!

**Comment by sjinzh** [comment]
> > > Hi @sjinzh! Would you like to be the reviewer for Zig and Rust?
> > 
> > 
> > @krahets Sure I would. It's my honour. Thanks!
> 
> Great! I'll mention you in the PRs related to Zig and Rust. You can comment in the PR. Once you approve it, I'll merge it.
> 
> And I plan to add a "Acknowledgements" block to the HelloAlgo site.
> 
> Thank you!

Great! Thanks!

**Comment by krahets** [comment]
@sjinzh Do you have WeChat, mine `krahets-jyd`

**Comment by krahets** [comment]
A Rust PR https://github.com/krahets/hello-algo/pull/332

**Comment by sjinzh** [comment]
> @sjinzh Do you have WeChat, mine `krahets-jyd`



> A Rust PR #332

OK. I will review this PR later.

**Pull request merged**
