### PR TITLE
Part Heap : Code Translation into C++ (my_heap.cpp)

### PR DESCRIPTION
**Pull request by longranger2**
If this PR is related to coding or code translation, please fill out the checklist.

 ✅  I've tested the code and ensured the outputs are the same as the outputs of reference codes.
 ✅  I've checked the codes (formatting, comments, indentation, file header, etc) carefully.
 ✅  The code does not rely on a particular environment or IDE and can be executed on a standard system (Win, macOS, Ubuntu).

我已经完成了my_heap.cpp，实现效果如下：
```C++
输入数组并建堆后
堆的数组表示：
[9, 8, 6, 6, 7, 5, 2, 1, 4, 3, 6, 2]
堆的树状表示：
        /——— 2
    /——— 6
   |    \——— 5
   |        \——— 2
——— 9
   |        /——— 6
   |    /——— 7
   |   |    \——— 3
    \——— 8
       |    /——— 4
        \——— 6
            \——— 1
堆顶元素为 9
元素 7 入堆后
堆的数组表示：
[9, 8, 7, 6, 7, 6, 2, 1, 4, 3, 6, 2, 5]
堆的树状表示：
        /——— 2
    /——— 7
   |   |    /——— 5
   |    \——— 6
   |        \——— 2
——— 9
   |        /——— 6
   |    /——— 7
   |   |    \——— 3
    \——— 8
       |    /——— 4
        \——— 6
            \——— 1
堆顶元素 7 出堆后
堆的数组表示：
[8, 7, 7, 6, 6, 6, 2, 1, 4, 3, 5, 2]
堆的树状表示：
        /——— 2
    /——— 7
   |    \——— 6
   |        \——— 2
——— 8
   |        /——— 5
   |    /——— 6
   |   |    \——— 3
    \——— 7
       |    /——— 4
        \——— 6
            \——— 1
堆顶元素数量为 12
堆是否为空 0
```
image

### CODE REVIEW

**Comment by longranger2** [comment]
I want to ask a question: the name of function need to be aligned with the java implementation? The name of function in my code is aligned with the C++ priority_queue
image

**Review by krahets — APPROVED** [review]

**Comment by krahets** [comment]
> I want to ask a question: the name of function need to be aligned with the java implementation? The name of function in my code is aligned with the C++ priority_queue image

We follow the naming style of Java. Because the function name is likely to be shown in the articles, we want to make all the names consistent.

**Comment by krahets** [comment]
I fine-tuned the codes and comments. Please check it.

Thanks for the PR!

**Comment by longranger2** [comment]
Got it. I will pay attention next time I contribute a PR 😄

**Comment by what-is-me** [comment]
Hello, I think you should add
`freeMemoryTree(root);`
to the end of the method `MaxHeap::print()` in line 116 in `my_heap.cpp`
and also to the function `printHeap()`
or there will be a little memory leak.

**Comment by longranger2** [comment]
> Hello, I think you should add `freeMemoryTree(root);` to the end of the method `MaxHeap::print()` in line 116 in `my_heap.cpp` and also to the function `printHeap()` or there will be a little memory leak.

Great! Thank you for your advice. I will fix it later.

**Comment by what-is-me** [comment]
Another suggestion：
I saw you write
```cpp
// 判空处理
if (empty()) {
    cout << "Error:堆为空" << endl;
    return;
}
```
to deal with heap_empty error.
However, in java or other language, when the error occurred, the procedure may exit.
Maybe a better way is to use `std::exception` like
```cpp
// 判空处理
if (empty()) throw out_of_range("堆为空");
```

**Comment by longranger2** [comment]
> Another suggestion： I saw you write
> 
> ```c++
> // 判空处理
> if (empty()) {
>     cout << "Error:堆为空" << endl;
>     return;
> }
> ```
> 
> to deal with heap_empty error. However, in java or other language, when the error occurred, the procedure may exit. Maybe a better way is to use `std::exception` like
> 
> ```c++
> // 判空处理
> if (empty()) throw out_of_range("堆为空");
> ```

Thank you for your advice! I will fix it later!

**Pull request merged**
